language: python
python: "3.7"
go: "1.16"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/localstack

install:
  - set -e # fail fast
  - eval "$(gimme 1.16)" # install go 1.16
  - go get -u github.com/jstemmer/go-junit-report # to generate the test report
  - bin/install-aws-test
  - |
    (
      cd localstack
      make install
    )

script:
  - TF_LOG=warn bin/run-tests --include localstack-tests.incl.txt --exclude localstack-tests.excl.txt

after_script:
  - bin/create-report
