language: python
python: "3.7"
go: "1.16"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/localstack

install:
  - set -e # fail fast
  - eval "$(gimme 1.16)" # install go 1.16
  - bin/install-aws-test
  - |
    (
      cd localstack
      make install
    )

script:
  - bin/run-tests "TestAcc*"
