language: python
python: "3.7"
go: "1.16"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/localstack

install:
  - set -e # fail fast
  - mkdir -p $HOME/.cache/localstack
  - ls -la $HOME/.cache/localstack

script:
  - ls -la $HOME/.cache/localstack
  - bin/list-tests | tee $HOME/.cache/localstack/test-list.log
  - ls -la $HOME/.cache/localstack
