version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      DOWNLOAD_TEST_BIN: 1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: "Installing prerequisites"
          command: |
            sudo apt-get update
            sudo apt install -y python3.8 python3.8-dev libsasl2-dev

      # download/install and cache aws.test and localstack pip
      - restore_cache:
          keys:
            - localstack-cache
      - run: bin/install-aws-test
      - run:
          name: "Installing LocalStack"
          command: |
            cd localstack
            python3.8 -m venv .venv
            make install
            cd ..
      - save_cache:
          key: localstack-cache
          paths:
            - /home/circleci/.cache/localstack/
            - /home/circleci/.cache/pip/
      - run:
          name: "Preparing test suite"
          command: |
            pip3 install -r requirements
            python3.8 -m tests.generator

      # main test suite
      - run:
          name: "Run test suite"
          command: python3.8 -m pytest --workers 2 --tests-per-worker 4 tests/ -k 'BucketNotification or S3Bucket_basic'

#      # save build reports as artifacts
#      - run:
#          name: "Create reports"
#          when: always
#          command: |
#            pip3 install junit2html
#            bin/create-report
#            bin/create-report-html
#            mkdir -p /tmp/logs/tests
#            mkdir -p /tmp/results/
#            mv target/logs /tmp/logs
#            mv build/tests/*.html /tmp/report/tests
#            mv build/tests/*.xml /tmp/results
#
#      - store_test_results:
#          path: /tmp/results
#      - store_artifacts:
#          path: /tmp/report
#      - store_artifacts:
#          path: /tmp/report/tests

workflows:
  main:
    jobs:
      - build
