version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      DOWNLOAD_TEST_BIN: 1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: "Installing prerequisites"
          command: |
            sudo apt-get update
            sudo apt install -y python3.8 libsasl2-dev

      # download/install and cache aws.test and localstack pip
      - restore_cache:
          keys:
            - localstack-cache
      - run: bin/install-aws-test
      - run:
          name: "Installing LocalStack"
          command: |
            cd localstack
            virtualenv --python=`which python3.8` .venv
            make install
            cd ..
      - save_cache:
          key: localstack-cache
          paths:
            - /home/circleci/.cache/localstack/
            - /home/circleci/.cache/pip/

      # main test suite
      - run:
          name: "Run test suite"
          command: bin/run-tests -i localstack-tests.incl.txt

      # save build reports as artifacts
      - run:
          name: "Create reports"
          when: always
          command: |
            pip3 install junit2html
            bin/create-report
            bin/create-report-html
            mkdir -p /tmp/report/tests
            mkdir -p /tmp/results/
            mv build/report.html /tmp/report
            mv build/tests/*.html /tmp/report/tests
            mv build/tests/*.xml /tmp/results

      - store_test_results:
          path: /tmp/results
      - store_artifacts:
          path: /tmp/report
      - store_artifacts:
          path: /tmp/report/tests

workflows:
  main:
    jobs:
      - build
